### ISSUE TITLE
[Docs] deployment file 不能下载，显示无权限

### ISSUE THREAD

**Issue by x506616039** [StarRocks/docs.zh-cn#5738]
File: [/deployment/prepare_deployment_files.md](https://docs.starrocks.io/zh-cn/latest/deployment/prepare_deployment_files)

starocks下载不下来，显示没有权限下载

**Comment by EsoragotoSpirit** [comment]
Hi @x506616039, I suppose you were pulling the Docker image, and got `permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=starrocks%2Fartifacts-ubuntu&tag=3.0.1": dial unix /var/run/docker.sock: connect: permission denied`. This is because the user you are using on your local host does not have the `docker pull` permission. You can add `sudo` at the beginning of the command, for example, `sudo docker pull starrocks/artifacts-ubuntu:3.0.1`. If you do not have a `sudo` permission, please contact the admin of your local host.
